### ISSUE TITLE
PBSIM3 Doesn't Allow References >1 Billion Nucleotides Long

### ISSUE THREAD

**Issue by jwalewski** [yukiteruono/pbsim3#23]
Looking at the source code, it seems to be right here:
https://github.com/yukiteruono/pbsim3/blob/c0e07a61e1af707a5150b9da4930c4e684523de3/src/pbsim.cpp#L27

While this may seem like an odd complaint it matters for the simulation of very large genomes (>20Gb). 

Is there a reason why 1 billion is the limit? If not, what should the limit be? Would setting it to 5 billion result in other portions of the code crashing/ undefined behavior?

**Comment by yukiteruono** [comment]
Thank you for using PBSIM often.
FASTQ_NUM_MAX and FASTQ_LEN_MAX are set to avoid accidentally creating huge data. You can change them to larger values if the memory capacity of your environment allows.

**Comment by yukiteruono** [comment]
I made a mistake, your question was REF_SEQ_LEN_MAX. This can also be changed.

**Comment by jwalewski** [comment]
Hey, thanks so much! Will do!
