### ISSUE TITLE
line 8: 341073 Segmentation fault

### ISSUE THREAD

**Issue by tanger-code** [yukiteruono/pbsim3#28]
Hi.

I'm simulating the long reads using command: 
`pbsim 
--strategy wgs 
--method qshmm
 --qshmm /data/home/tangen/data/sim_small_variant/model/QSHMM-RSII.model 
--depth 5 
--genome /data/home/tangen/data/sim_small_variant/GCA_chr21.fa 
--prefix long_depth_5/sd`

But there is an error:
![image](https://github.com/yukiteruono/pbsim3/assets/74750242/63f1b27a-f0b7-4791-873c-7b57ec776401)

The pbsim version I used is v3.0.2, and v3.0.4 is the same.

**Comment by yukiteruono** [comment]
Thank you for using PBSIM3.
The cause cannot be determined from the error message. 
Is "long_depth_5" pre-created? (PBSIM3 does not create directories) 
Is the input files path correct? .

**Comment by tanger-code** [comment]
Sorry, there is an error when I copy the model file. It works now. Thank you!
