### ISSUE TITLE
median and quartile for length and accuracy

### ISSUE THREAD

**Issue by nicolo-tellini** [yukiteruono/pbsim3#30]
Hi,

In some cases real datasets can be strongly skewed, could be add the option to use `length/accuracy-median` and `length/accuracy-q1/q3` instead of `mean` and `sd` ? do you think this implementation is feasible and could be an improvement ? 

best

nic

**Comment by yukiteruono** [comment]
Thank you for using PBSIM3.
Your suggestion is possible to implement, but it seems not easy.
If I were to simulate strongly skewed data, I would generate several data sets with different parameters and combine them.
If you have real data you want to mimic, and it is not PacBio HiFi, I would recommend using sample-based simulation (see README). This will allow you to mimic the length and accuracy distribution of the real data.

**Comment by nicolo-tellini** [comment]
Ok! thanks for the suggestion
