### ISSUE TITLE
Question about parameter that controls the read length

### ISSUE THREAD

**Issue by Hendricks27** [yukiteruono/pbsim3#34]
Thank you for your previous response and for making the software available to us.

I have a quick question about the read length parameter. There are options to control the minimum, maximum, mean, and standard deviation. From the PBSIM and PBSIM3 papers, my understanding is that the read length distribution has shifted from a log-normal to a gamma distribution. If I have long-read real data and want to simulate a similar read length distribution, should I simply input the mean and standard deviation from the real data into PBSIM3? Will PBSIM3 automatically determine the shape parameters for the gamma distribution based on that information? 

Thanks again for your help.

**Comment by yukiteruono** [comment]
Thank you for using PBSIM3.
PBSIM3 generates a gamma distribution from the user-specified mean length and standard deviation, and randomly samples the read length from it.
If you want to imitate specific real read data, we recommend sampling-based simulation. In sampling-based simulation, a read is randomly sampled from the input real data set, and only the nucleotide sequence is replaced with a randomly sampled nucleotide sequence from the reference sequence to generate a new read. Therefore, the read length distribution and accuracy can be almost imitated, but the read length distribution may change if you specify the max and min of the read length.

**Comment by Hendricks27** [comment]
Thank you so much for the reply!
