### ISSUE TITLE
PbSim3 vs PbSim2

### ISSUE THREAD

**Issue by m5imunovic** [yukiteruono/pbsim3#5]
Is PbSim3 recommended over PbSim2 or is it still "work in progress"? Is there any documentation available on the differences between these two versions?

**Comment by yukiteruono** [comment]
Thank you for your using PBSIM.
Development of the first version of PBSIM3 has been completed. PBSIM3 implements three new functions. A paper describing these functions in detail has been submitted. All the functions of PBSIM2 are implemented in PBSIM3, and they work in almost the same way.

**Comment by m5imunovic** [comment]
Tnx. Is the paper available as a preprint?

**Comment by yukiteruono** [comment]
It is not available yet.
