### ISSUE TITLE
PacBio HiFi reads simulation

### ISSUE THREAD

**Issue by kisarur** [yukiteruono/pbsim3#8]
Hi, I'm intending to use pbsim3 to generate PacBio HiFi/CCS reads. Could you recommend the parameters to be used for this reads simulation?

I'm currently planning to use pbsim3 with the parameters below (parameters were derived from the detailed mentioned in the paper at https://academic.oup.com/nargab/article/4/4/lqac092/6855700) and send the resulting .sam file to ccs software from PacBio. Please let me know if the below command looks fine.

`./pbsim --strategy wgs --method qshmm --qshmm data/QSHMM-RSII.model --difference-ratio 22:45:33 --length-mean 15000 --depth 5 --genome hg38noAlt.fa --pass-num 10`

Thank you!

**Comment by yukiteruono** [comment]
Thank you for your using PBSIM3.
If simulating genome assembly, the coverage depth is too small. If you select an appropriate coverage depth for your purpose, your command is fine.

**Comment by kisarur** [comment]
Great, thank you very much for the help!

**Comment by zhuyixin43** [comment]
Hi there, I am also trying to stimulate hifi reads from a genome. and I have a followup question to this problem. After I run pbsim3, I get multiple sam files. Do I merge them into one big sam file and then feed it as input to ccs software?

I'm a little confused about how the next steps. It will also be great if you could provide an example downstream ccs command.
Thank you so much
